### ISSUE TITLE
python-trezor-0.7.13 crashes electrum-2.8.2

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#111]
0.7.12 did not trigger this issue, I am surprised since there was only a bump in the patch number. 

```
$ electrum 
"sni-qt/15815" WARN  23:53:25.727 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/bin/electrum", line 379, in <module>
    d.init_gui(config, plugins)
  File "/usr/lib/python2.7/site-packages/electrum/daemon.py", line 282, in init_gui
    self.gui.main()
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 199, in main
    if not self.start_new_window(path, self.config.get('url')):
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 156, in start_new_window
    wallet = self.daemon.load_wallet(path, None)
  File "/usr/lib/python2.7/site-packages/electrum/daemon.py", line 219, in load_wallet
    wallet = Wallet(storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1756, in __new__
    wallet = WalletClass(storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1563, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1408, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 103, in __init__
    self.load_keystore()
  File "/usr/lib/python2.7/site-packages/electrum/wallet.py", line 1530, in load_keystore
    self.keystore = load_keystore(self.storage, 'keystore')
  File "/usr/lib/python2.7/site-packages/electrum/keystore.py", line 617, in load_keystore
    k = hardware_keystore(d)
  File "/usr/lib/python2.7/site-packages/electrum/keystore.py", line 601, in hardware_keystore
    return constructor(d)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 169, in dynamic_constructor
    return self.get_plugin(name).keystore_class(d)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 177, in get_plugin
    self.load_plugin(name)
  File "/usr/lib/python2.7/site-packages/electrum/plugins.py", line 102, in load_plugin
    plugin = p.Plugin(self, self.config, name)
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/trezor.py", line 16, in __init__
    import client
  File "/usr/lib/python2.7/site-packages/electrum_plugins/trezor/client.py", line 1, in <module>
    from trezorlib.client import proto, BaseClient, ProtocolMixin
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 34, in <module>
    from . import mapping
  File "/usr/lib/python2.7/site-packages/trezorlib/mapping.py", line 19, in <module>
    from . import messages_pb2 as proto
  File "/usr/lib/python2.7/site-packages/trezorlib/messages_pb2.py", line 17, in <module>
    from . import types_pb2 as types__pb2
  File "/usr/lib/python2.7/site-packages/trezorlib/types_pb2.py", line 26, in <module>
    dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by hegjon** [comment]
Environment: Fedora 25 x86-64, installed via RPM packages.

**Comment by prusnak** [comment]
This is a protobuf issue, not python-trezor.

See:
* https://github.com/tensorflow/tensorflow/issues/57
* https://stackoverflow.com/questions/33622842/error-in-python-after-import-tensorflow-typeerror-init-got-an-unexpect
* etc.

**Comment by hegjon** [comment]
Thanks, I will look deeper into it

**Comment by hegjon** [comment]
Version 0.7.12 runs without any exceptions, while 0.7.13 causes this error. The protobuf-python version is the same. Could it be the way the generated protobuffer code is generated? Did you run with different versions of protobuf-compiler when running build_pb.sh?

**Comment by prusnak** [comment]
Ah, you might be on the right track. There was a commit (29348f40980f3ec78c32d2161ea62d22cf2db4af) between 0.7.12 and 0.7.13 where I regenerated protobufs and most probably python-protobuf version changed from 2.x to 3.x.

Maybe we shoud bump the requirement for python-protobuf to 3.x series.

Would that be OK?

**Comment by hegjon** [comment]
That is fine, I am glad we have probably found the issue.

Fedora 25 ships with protobuf 2.5 as system package, but I have the option to run the protoc commands during the build. Will that cause problems? I probably need to create a package or bundle the protobuf messages.

**Comment by prusnak** [comment]
It probably should not cause problems if user does not mix trezor package from fedora with trezor package from pypi.
