### ISSUE TITLE
trezorctl set_homescreen broken in master? 

### ISSUE THREAD

**Issue by molecular** [trezor/python-trezor#122]
set_homescreen doesn't work with python3.

```
~/bitcoin/python-trezor\> ./trezorctl set_homescreen -f test.png
Traceback (most recent call last):
  File "./trezorctl", line 649, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "./trezorctl", line 204, in set_homescreen
    return client.apply_settings(homescreen=img)
  File "/home/nick/bitcoin/python-trezor/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/nick/bitcoin/python-trezor/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/nick/bitcoin/python-trezor/trezorlib/client.py", line 621, in apply_settings
    settings.homescreen = homescreen
  File "/usr/lib/python3.6/site-packages/protobuf-3.3.0-py3.6.egg/google/protobuf/internal/python_message.py", line 661, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/usr/lib/python3.6/site-packages/protobuf-3.3.0-py3.6.egg/google/protobuf/internal/type_checkers.py", line 109, in CheckValue
    raise TypeError(message)
TypeError: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07ÿÿÿÿÿÿÿÿÿÿÿÿÿþ\x00\x03ÿÿÿÿÿÿÿÿÿÿÿÿÿþ\x00\x07ÿÿÿÿÿÿÿÿÿÿÿÿÿü\x00\x07û»»»»»»»»»»»»ü\x00\x07À\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1c\x00\x0f\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x0f\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x0f\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x008\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x008\x00\x1f\x00\x00\x00\x00\x00\x1e\x1f\x00\x00\x00\x00\x00\x00x\x00\x0f\x00\x00\x00\x00\x00\x1e\x1e\x00\x00\x00\x00\x00\x008\x00\x1f\x00\x00\x00\x00\x00<\x1e\x00\x00\x00\x00\x00\x00x\x00\x1e\x00\x00\x00\x00\x00>>\x00\x00\x00\x00\x00\x00x\x00\x1f\x00\x00\x00\x00\x00<\x1c\x00\x00\x00\x00\x00\x00p\x00\x1e\x00\x00\x00\x00\x008<\x00\x00\x00\x00\x00\x00ð\x00>\x00\x00\x00\x00\x00||\x00\x00\x00\x00\x00\x00ð\x00>\x00\x00\x00\x00\x008<\x00\x00\x00\x00\x00\x00à\x00<\x00\x07þ\x00\x07ÿÿü\x00\x01ÿÿñð\x00<\x00\x0fþ\x has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)
```

tried converting the "img" of type str to "bytes" in trezorctl:204, but need to give encoding ('utf-8' leads to 'bytes overflow', 'ascii' leads to 'ordinal not in range')

any fix for this?

(I saw the issue about strings/bytes regarding python3 but cannot make enough sense)

What's the youngest version (tag) that works with python2?

**Comment by prusnak** [comment]
I'll look into that.
For the time being, the 0.7.x branch should work with Python 2.

**Comment by molecular** [comment]
this worked for me:

```
diff --git a/trezorctl b/trezorctl
index 2aa2e5c..e055ffd 100755
--- a/trezorctl
+++ b/trezorctl
@@ -187,6 +187,7 @@ def set_label(client, label):
 @click.option('-f', '--filename', default=None)
 @click.pass_obj
 def set_homescreen(client, filename):
+    import codecs
     if filename is not None:
         from PIL import Image
         im = Image.open(filename)
@@ -195,13 +196,15 @@ def set_homescreen(client, filename):
         im = im.convert('1')
         pix = im.load()
         img = ''
+        img_bytes = bytearray(b'');
         for j in range(64):
             for i in range(128):
                 img += '1' if pix[i, j] else '0'
-        img = ''.join(chr(int(img[i:i + 8], 2)) for i in range(0, len(img), 8))
+        for i in range(0, len(img), 8):
+            img_bytes.append( int(img[i:i + 8], 2) )
     else:
         img = '\x00'
-    return client.apply_settings(homescreen=img)
+    return client.apply_settings(homescreen=bytes(img_bytes))
 
 
 @cli.command(help='Set U2F counter.')
```

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/python-trezor/commit/afdd27c551eda671c8698344d4be72deba1fb734 in slightly different manner

Thanks!
