### ISSUE TITLE
trezorctl crashes when I run recover_device with -t matrix

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#128]
Pressing a number or pressing the left key will cause this error:

Version: 0.7.16 (via Fedora package)

```
$ trezorctl recovery_device -t matrix
Use the numeric keypad to describe positions.  For the word list use only left and right keys. The layout is:
    7 8 9     7 | 9
    4 5 6     4 | 6
    1 2 3     1 | 3
Traceback (most recent call last):
  File "/usr/bin/trezorctl", line 618, in <module>
    main()
  File "/usr/bin/trezorctl", line 603, in main
    res = args.func(cmds, args)
  File "/usr/bin/trezorctl", line 280, in recovery_device
    typemap[args.type], args.expand, args.dry_run)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 873, in recovery_device
    dry_run=dry_run))
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 201, in call
    msg = handler(resp)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 295, in callback_WordRequest
    return self.callback_RecoveryMatrix(msg)
  File "/usr/lib/python2.7/site-packages/trezorlib/client.py", line 257, in callback_RecoveryMatrix
    if (isinstance(msg.type, types.WordRequestType_Matrix6) and character in ('2', '5', '8')):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by hegjon** [comment]
Sorry, seems like it have been fixed on master
