### ISSUE TITLE
Dry-run recovery does not work with matrix word input

### ISSUE THREAD

**Issue by xbach** [trezor/python-trezor#135]
Not sure if fixed and unreleased.

`trezorctl recovery_device --dry-run -t matrix`

```
Traceback (most recent call last):
  File "/Users/xbach/bin/trezorenv/bin/trezorctl", line 618, in <module>
    main()
  File "/Users/xbach/bin/trezorenv/bin/trezorctl", line 603, in main
    res = args.func(cmds, args)
  File "/Users/xbach/bin/trezorenv/bin/trezorctl", line 280, in recovery_device
    typemap[args.type], args.expand, args.dry_run)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 873, in recovery_device
    dry_run=dry_run))
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 204, in call
    resp = self.call(msg)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 201, in call
    msg = handler(resp)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 295, in callback_WordRequest
    return self.callback_RecoveryMatrix(msg)
  File "/Users/xbach/bin/trezorenv/lib/python3.5/site-packages/trezorlib/client.py", line 257, in callback_RecoveryMatrix
    if (isinstance(msg.type, types.WordRequestType_Matrix6) and character in ('2', '5', '8')):
TypeError: isinstance() arg 2 must be a type or tuple of types

```

**Comment by prusnak** [comment]
Fixed, but not released yet.
