### ISSUE TITLE
Unable to Setup New Trezor: "OSError: open failed"

### ISSUE THREAD

**Issue by xanderdunn** [trezor/python-trezor#196]
I'm on a 2017 MacBook Pro with macOS High Sierra 10.13.2.  I'm setting up this trezor for the first time.

```
$ pip --version
pip 9.0.1 from /usr/local/anaconda3/lib/python3.6/site-packages (python 3.6)
$ trezorctl list
b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/TREZOR@14410000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14410000,0'
$ trezorctl reset_device
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/trezorctl", line 618, in <module>
    main()
  File "/usr/local/anaconda3/bin/trezorctl", line 595, in main
    transport = get_transport(args.transport, args.path)
  File "/usr/local/anaconda3/bin/trezorctl", line 90, in get_transport
    return HidTransport(d, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 166, in HidTransport
    return transport(device, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 72, in __init__
    super(_HidTransport, self).__init__(device, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport.py", line 39, in __init__
    self._open()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 85, in _open
    self.hid.open_path(self.device)
  File "hid.pyx", line 72, in hid.device.open_path (hid.c:1909)
OSError: open failed
```

I get the same error on other commands I try: `trezorctl wipe_device` and `trezorctl update_firmware`.

I have trezord 1.2.1 installed and running from [here](https://wallet.trezor.io/data/bridge/latest/index.html).

Note that I'm also unable to set it up at trezor.io/wallet using the Chrome extension.  See [here](https://github.com/trezor/trezor-chrome-extension/issues/20)

**Comment by prusnak** [comment]
Please contact our support, Github is not a support channel.

**Comment by prusnak** [comment]
I would suggest you trying a different USB cable.

Also if you run bridge, you cannot use python-trezor or chrome extension as the device is fully locked by the bridge.

**Comment by xanderdunn** [comment]
Thanks.  

Is there anywhere I can suggest improvements to the documentation?  It seems important to mention that the Trezor bridge is mutually exclusive to trezorctl and the Chrome extension.

**Comment by xanderdunn** [comment]
I'll continue to post my results here so that hopefully it can help someone else in the future.  

I get the same error after uninstalling trezord and rebooting + making sure that it's not running. 
 
I'm using [this](https://www.apple.com/shop/product/MJ1K2AM/A/usb-c-digital-av-multiport-adapter?fnode=8b) USB adapter sold by Apple.  Tomorrow I'll try the other one Apple sells.

**Comment by prusnak** [comment]
Documentation is maintained here: https://github.com/satoshilabs/docs

**Comment by xanderdunn** [comment]
I get the same results using [this](https://www.apple.com/shop/product/MJ1M2AM/A/usb-c-to-usb-adapter?fnode=8b) USB adapter from Apple:

```
$ trezorctl list
b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS11@14600000/TREZOR@14600000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14600000,0'
xander@Xanders-Personal-MacBook-Pro ~ $ trezorctl reset_device
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/trezorctl", line 618, in <module>
    main()
  File "/usr/local/anaconda3/bin/trezorctl", line 595, in main
    transport = get_transport(args.transport, args.path)
  File "/usr/local/anaconda3/bin/trezorctl", line 90, in get_transport
    return HidTransport(d, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 166, in HidTransport
    return transport(device, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 72, in __init__
    super(_HidTransport, self).__init__(device, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport.py", line 39, in __init__
    self._open()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 85, in _open
    self.hid.open_path(self.device)
  File "hid.pyx", line 72, in hid.device.open_path (hid.c:1909)
OSError: open failed
```

<img width="1680" alt="screen shot 2018-01-05 at 13 47 27" src="https://user-images.githubusercontent.com/1313618/34629957-fbc6a8d6-f21e-11e7-8264-35dd5a77047c.png">

Is there a USB adapter that's been successfully tested with 2017 MacBook Pros?

I've sent an email to support@trezor.io.

**Comment by saleemrashid** [comment]
@xanderdunn When you run the `trezorctl` command, could you make sure that Chrome is closed? It might have opened the HID device, preventing `trezorctl` from using it.

**Comment by xanderdunn** [comment]
@saleemrashid Thanks!  Unfortunately, same result with chrome closed:

```
```

**Comment by prusnak** [comment]
Please close the support ticket if we are going to be solving it here, or please close the issue if you want to solve it in our ticket system, thanks!

**Comment by prusnak** [comment]
I would suggest to try it without the usb adapter, just with a cable.

**Comment by xanderdunn** [comment]
Thanks, I've purchased [this](https://www.amazon.com/gp/product/B00UUBRX0Y/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1) cable.  We'll see how it works. 

It seems worth testing trezor with the above Apple adaptors, they're what everyone with a new MacBook Pro will be using.  

I asked the support email address to close my support ticket.

**Comment by xanderdunn** [comment]
I get the same result with the [Amazon USB-C to micro USB cable](https://www.amazon.com/gp/product/B00UUBRX0Y/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1):
```
$ trezorctl list
b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/TREZOR@14400000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14400000,0'
$ trezorctl reset_device
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/trezorctl", line 618, in <module>
    main()
  File "/usr/local/anaconda3/bin/trezorctl", line 595, in main
    transport = get_transport(args.transport, args.path)
  File "/usr/local/anaconda3/bin/trezorctl", line 90, in get_transport
    return HidTransport(d, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 166, in HidTransport
    return transport(device, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 72, in __init__
    super(_HidTransport, self).__init__(device, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport.py", line 39, in __init__
    self._open()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/trezorlib/transport_hid.py", line 85, in _open
    self.hid.open_path(self.device)
  File "hid.pyx", line 72, in hid.device.open_path (hid.c:1909)
OSError: open failed
```

Surely other people are having success on MacBook Pros?   Is it possible my trezor is defunct? It seems to turn on fine when I plug it in:
![12bd9f60-334e-4bd9-9bc4-eefd6ae7ebb9](https://user-images.githubusercontent.com/1313618/34713142-1fd9bb4c-f4da-11e7-9a87-263d339cdc14.JPG)

Are there any logs I can collect for you?

**Comment by prusnak** [comment]
Try it on different computer. If it does not work, it's defunct and you
should ask for a replacement.

**Comment by xanderdunn** [comment]
This ended up just being a bad unit.  I purchased a new one and it worked perfectly fine with all the cables.  No issues.

**Comment by kwccoin** [comment]
I am not sure it is bad Trezor unless macos make it bad.  The same trezor of mine work fine before and after not worlking with the trezor device under macos.  There is message about hid using the apple apple-c-usb.  The trezor pop up the keypad but the chrome refuse to talk to it
