### ISSUE TITLE
OSX Yosemite protobuf issue

### ISSUE THREAD

**Issue by usezfsyo** [trezor/python-trezor#20]
After installing with 'sudo python setup.py install' and running helloworld.py with Trezor attached:

Traceback (most recent call last):
  File "./helloworld.py", line 3, in <module>
    from trezorlib.client import TrezorClient
  File "/Users/user/src/python-trezor/trezorlib/client.py", line 7, in <module>
    import mapping
  File "/Users/user/src/python-trezor/trezorlib/mapping.py", line 1, in <module>
    import messages_pb2 as proto
  File "/Users/user/src/python-trezor/trezorlib/messages_pb2.py", line 4, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal

Install log is here, seems to pick the right protobuf version (2.5.0):
http://pastebin.com/qqw4tyGh

**Comment by prusnak** [comment]
Just tested on Yosemite.

```
easy_install protobuf==2.5.0
```

works correctly.
