### ISSUE TITLE
trezorlib version problem

### ISSUE THREAD

**Issue by allanchow** [trezor/python-trezor#206]
This is my first issue. 
I installed trezor-agent but found the following issue, I followed the link below
[](https://github.com/romanz/trezor-agent/issues/191
)
and type in pip install -e git+https://github.com/trezor/python-trezor.git#egg=trezor and it eventually works.
May I know why I am using pip instead of pip3 and when trezorlib version will be fixed?
Thank you.
```
2018-01-22 17:39:51,144 WARNING      error: No module named 'trezorlib.messages'                                                          [server.py:63]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/lib/python3.5/dist-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/lib/python3.5/dist-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/lib/python3.5/dist-packages/libagent/ssh/__init__.py", line 186, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/lib/python3.5/dist-packages/libagent/ssh/__init__.py", line 180, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.5/dist-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.5/dist-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.5/dist-packages/libagent/device/trezor.py", line 107, in connect
    for transport in self._defs.Transport.enumerate():
  File "/usr/local/lib/python3.5/dist-packages/libagent/device/trezor.py", line 44, in _defs
    from . import trezor_defs
  File "/usr/local/lib/python3.5/dist-packages/libagent/device/trezor_defs.py", line 7, in <module>
    from trezorlib.messages import IdentityType, PassphraseAck, PinMatrixAck
ImportError: No module named 'trezorlib.messages'
````

**Comment by romanz** [comment]
`trezor-agent` and `python-trezor` support Python 3 - so you should be able to use `pip3` to install them.

**Comment by prusnak** [comment]
Just use pip3 instead of of pip.
