### ISSUE TITLE
Problem running the helloworld.py

### ISSUE THREAD

**Issue by Quenos** [trezor/python-trezor#208]
I'm trying to run helloworld.py but get the following error message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 157, i
n wrapped_f
    client.transport.session_begin()
AttributeError: 'list' object has no attribute 'session_begin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 231, in <module>
    main()
  File "test.py", line 170, in main
    client = TrezorClient(transport)
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 451, i
n __init__
    self.init_device()
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 458, i
n init_device
    self.features = expect(proto.Features)(self.call)(proto.Initialize())
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 144, i
n wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 160, i
n wrapped_f
    client.transport.session_end()
AttributeError: 'list' object has no attribute 'session_end'
coen@Soproni:~/PycharmProjects/AirTrezor$ python3 test.py 2>&1 >/dev/null   | more
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 157, i
n wrapped_f
    client.transport.session_begin()
AttributeError: 'list' object has no attribute 'session_begin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 40, in <module>
    main()
  File "test.py", line 24, in main
    client = TrezorClient(transport)
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 451, i
n __init__
    self.init_device()
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 458, i
n init_device
    self.features = expect(proto.Features)(self.call)(proto.Initialize())
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 144, i
n wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 160, i
n wrapped_f
    client.transport.session_end()
AttributeError: 'list' object has no attribute 'session_end'

**Comment by slush0** [comment]
Hello, please try git master, it works for me for python3. Since latest pypi release there was many changes and fixes for python3....

python-trezor does not work in python2, which is EOL anyway.

**Comment by Quenos** [comment]
Maybe I am a bit slow, but what master repo do you mean?
I’m on python-trezor master.

**Comment by saleemrashid** [comment]
@Quenos What command did you use to install the library?

**Comment by Quenos** [comment]
@saleemrashid 
sudo -H pip install setuptools
sudo -H pip install -r requirements.txt
sudo -H pip install trezor

**Comment by saleemrashid** [comment]
@Quenos That installs `treozrlib` from PyPI, not from `master`. Either checkout the tag `v0.7.16` in the Git repository, or use `pip install git+https://github.com/trezor/python-trezor.git` to install it form `master`.

**Comment by Quenos** [comment]
@saleemrashid Got the following error after a clean install and command trezorctl getfeatures:

trezorctl get_features
Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 879, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/bin/trezorctl", line 180, in get_features
    return connect().features
  File "/usr/local/bin/trezorctl", line 105, in <lambda>
    ctx.obj = lambda: TrezorClient(get_transport(transport, path))
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 451, in __init__
    self.init_device()
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 458, in init_device
    self.features = expect(proto.Features)(self.call)(proto.Initialize())
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 137, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/client.py", line 149, in wrapped_f
    client.transport.session_begin()
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/transport.py", line 34, in session_begin
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/transport_hid.py", line 118, in open
    self.hid.open()
  File "/usr/local/lib/python3.5/dist-packages/trezorlib/transport_hid.py", line 44, in open
    self.handle.open_path(self.path)
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed

**Comment by Quenos** [comment]
should run as sudo :)

works!

**Comment by saleemrashid** [comment]
> should run as sudo :)

Should install udev rules :)

 https://github.com/trezor/trezor-common/blob/master/udev/51-trezor.rules
