### ISSUE TITLE
Exception: Got <class 'trezorlib.messages_pb2.Success'>, expected (<class 'trezorlib.messages_pb2.CipheredKeyValue'>,)

### ISSUE THREAD

**Issue by electrumTrezor** [trezor/python-trezor#26]
```
john@ubuntu:~$ sudo encfs --standard --extpass=~/python-trezor/tools/encfs_aes_getpass.py ~/.trezor ~/trezor
/usr/local/lib/python2.7/dist-packages/hidapi-0.7.99_5-py2.7-linux-x86_64.egg/hid.py:3: UserWarning: Module trezorlib was already imported from /usr/local/lib/python2.7/dist-packages/trezor-0.6.3-py2.7.egg/trezorlib/__init__.pyc, but /usr/local/lib/python2.7/dist-packages/python_trezor-0.5.0-py2.7.egg is being added to sys.path
Please provide label for new drive: trezor
Computer asked Trezor for new strong password.
Please confirm action on your device.
Traceback (most recent call last):
  File "/home/david/python-trezor/tools/encfs_aes_getpass.py", line 113, in <module>
    main()
  File "/home/david/python-trezor/tools/encfs_aes_getpass.py", line 93, in main
    passw_encrypted = client.encrypt_keyvalue(bip32_path, label, passw, False, True)
  File "/usr/local/lib/python2.7/dist-packages/trezor-0.6.3-py2.7.egg/trezorlib/client.py", line 68, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/trezor-0.6.3-py2.7.egg/trezorlib/client.py", line 84, in wrapped_f
    raise Exception("Got %s, expected %s" % (ret.__class__, self.expected))
Exception: Got <class 'trezorlib.messages_pb2.Success'>, expected (<class 'trezorlib.messages_pb2.CipheredKeyValue'>,)
```
Does anyone know why this is happening?

**Comment by prusnak** [comment]
You are using old TREZOR firmware. Update to 1.3.0 or later.
