### ISSUE TITLE
Question: what does this mean: TypeError: 'message' has type str, but expected one of: bytes"

### ISSUE THREAD

**Issue by jcalfee** [trezor/python-trezor#265]
How do I pass in "bytes" ?

```bash
trezorctl encrypt_keyvalue "My Altcoin Seed" "message"
Traceback (most recent call last):
  File "/usr/bin/trezorctl", line 618, in <module>
    main()
  File "/usr/bin/trezorctl", line 603, in main
    res = args.func(cmds, args)
  File "/usr/bin/trezorctl", line 341, in encrypt_keyvalue
    ret = self.client.encrypt_keyvalue(address_n, args.key, args.value)
  File "/usr/lib/python3/dist-packages/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/trezorlib/client.py", line 676, in encrypt_keyvalue
    iv=iv))
TypeError: 'message' has type str, but expected one of: bytes
```

**Comment by prusnak** [comment]
@matejcik seems like a conversion is missing?
