### ISSUE TITLE
trezorctl list_coins didn't work?

### ISSUE THREAD

**Issue by bernardpeh** [trezor/python-trezor#277]
trezorctl list_coins
Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 1056, in <module>
    cli()  # pylint: disable=E1120
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/bin/trezorctl", line 178, in list_coins
    return [coin.coin_name for coin in connect().features.coins]
  File "/usr/local/lib/python3.6/site-packages/trezorlib/protobuf.py", line 160, in __getattr__
    raise AttributeError(attr)
AttributeError: coins

**Comment by prusnak** [comment]
Correct. TREZOR now doesn't return the list of supported coins. The `list_coins` command should be removed. // cc @matejcik

**Comment by bernardpeh** [comment]
how to return list of coins then?

**Comment by prusnak** [comment]
You look here to see which coin is supported from which version of FW.
