### ISSUE TITLE
I tried to get Decred address with Model T 1.6.2, There is something wrong.

### ISSUE THREAD

**Issue by 0x5826** [trezor/python-trezor#285]
**sudo trezorctl get_address --coin Decred  --script-type address  --address "m/42'/0'/0'/0/0"**
Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 1059, in <module>
    cli()  # pylint: disable=E1120
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/bin/trezorctl", line 505, in get_address
    return client.get_address(coin, address_n, show_display, script_type=script_type)
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/client.py", line 100, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/client.py", line 115, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/client.py", line 483, in get_address
    return self.call(proto.GetAddress(address_n=n, coin_name=coin_name, show_display=show_display, script_type=script_type))
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/client.py", line 131, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/client.py", line 174, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/client.py", line 186, in callback_Failure
    raise CallException(msg.code, msg.message)
trezorlib.client.CallException: (99, 'Firmware error')

**Comment by matejcik** [comment]
Decred is not supported on Trezor T yet. The listing on https://trezor.io/coins is wrong in this case.
