### ISSUE TITLE
Stellar_get_address not working ?

### ISSUE THREAD

**Issue by Ch1p999** [trezor/python-trezor#290]
I checked trezorctl has stellar_get_address and tried to create an address but its returning error 
Am I doing anything wrong or is this feature still not implemented 

- Installed python-trezor using pip3 
- Using a model T
- Version 2.0.7

```
trezorctl stellar_get_address -n "m/44'/148'/0" -d
Traceback (most recent call last):
  File "/var/www/html/tz-stellar/bin/trezorctl", line 1059, in <module>
    cli()  # pylint: disable=E1120
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/var/www/html/tz-stellar/bin/trezorctl", line 1027, in stellar_get_address
    return client.stellar_get_address(address_n, show_display)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/trezorlib/client.py", line 100, in wrapped_f
    ret = f(*args, **kwargs)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/trezorlib/client.py", line 115, in wrapped_f
    ret = f(*args, **kwargs)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/trezorlib/client.py", line 1106, in stellar_get_address
    return self.call(proto.StellarGetAddress(address_n=address_n, show_display=show_display))
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/trezorlib/client.py", line 131, in wrapped_f
    return f(*args, **kwargs)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/trezorlib/client.py", line 174, in call
    msg = handler(resp)
  File "/var/www/html/tz-stellar/lib/python3.6/site-packages/trezorlib/client.py", line 186, in callback_Failure
    raise CallException(msg.code, msg.message)
trezorlib.client.CallException: (1, 'Unexpected message')

```

**Comment by prusnak** [comment]
Stellar is not implemented in the released 2.0.7 firmware. It will be
available in the next firmware update.
