### ISSUE TITLE
./trezorctl sign-tx non functional for most networks

### ISSUE THREAD

**Issue by tarpas** [trezor/python-trezor#323]
I get this exception on bitcoin (and I assume almost all other coins)
```
(python-trezor-gq2D8zhy) bash-3.2$ ./trezorctl sign-tx -c Bitcoin

Previous output to spend (txid:vout) []:  2d5a66e4b070e37a8f0f5200ba8f64000c3afb55dd0bc8073b3f8b5a96323d59:0
BIP-32 path to derive the key: m/44'/289'/0'/0/1    
Input amount (satoshis) [0]: 4507189
Sequence Number to use (RBF opt-in enabled by default) [4294967293]: 
Input type (address, segwit, p2shsegwit) [address]: 

Previous output to spend (txid:vout) []: 

Output address (for non-change output) []: 35ZM7DJz2mr1xnEzzWJ6iHuojPQ8cVs8NF
Amount to spend (satoshis): 4407189                           
Output type (address, segwit, p2shsegwit) [address]: 
Traceback (most recent call last):
  File "./trezorctl", line 1744, in <module>
    cli()  # pylint: disable=E1120
  File "/Users/tibor/.virtualenvs/python-trezor-gq2D8zhy/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tibor/.virtualenvs/python-trezor-gq2D8zhy/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/tibor/.virtualenvs/python-trezor-gq2D8zhy/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tibor/.virtualenvs/python-trezor-gq2D8zhy/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tibor/.virtualenvs/python-trezor-gq2D8zhy/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/tibor/.virtualenvs/python-trezor-gq2D8zhy/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "./trezorctl", line 871, in sign_tx
    block_hash_bip115=block_hash[::-1],  # Blockhash passed in reverse order
UnboundLocalError: local variable 'block_hash' referenced before assignment
```

**Comment by prusnak** [comment]
Fixed via 1a239201d8751664d6a0030859c3d0fbd524e2a0

Thanks!
