### ISSUE TITLE
zcash v4 support in tx_api

### ISSUE THREAD

**Issue by matejcik** [trezor/python-trezor#367]
two sub-issues:
1. blockbook fields `fOverwintered` and friends got renamed, we need to fix that
2. for v4 we need more extra_data. i'm honestly considering counting raw tx bytes and just stuffing the whole suffix into extra_data

**Comment by matejcik** [comment]
correction: we should not need to ever send extra_data now, given that only overwintered transactions are legal and these don't need prev-txes

that means that the Zcash-specific code in tx_api might be candidate for removal?

**Comment by tokyotechlab** [comment]
nExpiryHeight and nVersionGroupId also got renamed. I'm doing the following in tx_api.py

    if is_zcash(coin):
        #t.overwintered = data.get("fOverwintered", False)
        #t.expiry = data.get("nExpiryHeight", None)
        #t.version_group_id = data.get("nVersionGroupId", None)

        t.overwintered = data.get("overwintered", False)
        t.expiry = data.get("expiryheight", None)
        t.version_group_id = int(data.get("versiongroupid", None), 16)

**Comment by tokyotechlab** [comment]
Even then, I'm still getting the following error when I try to spend zcash v4 transactions.

[2019-04-20 23:14:17,108] trezorlib.transport.protocol DEBUG: sending message: TxAck
TxAck (36 bytes) {
    tx: TransactionType (34 bytes) {
        bin_outputs: [
            TxOutputBinType (32 bytes) {
                amount: 4496100,
                script_pubkey: 25 bytes 0x76a9140a045f124e12c808ab29ac60fa6860fecb1aff9088ac,
            },
        ],
    },
}
[2019-04-20 23:14:17,128] trezorlib.transport.protocol DEBUG: received message: Failure
Failure (33 bytes) {
    code: 9,
    message: 'Encountered invalid prev_hash',
}
Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 1989, in <module>
    cli()  # pylint: disable=E1120
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/bin/trezorctl", line 868, in sign_tx
    client, coin, inputs, outputs, details, prev_txes
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/tools.py", line 233, in wrapped_f
    return f(client, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/btc.py", line 176, in sign_tx
    res = client.call(messages.TxAck(tx=msg))
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/tools.py", line 233, in wrapped_f
    return f(client, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trezorlib/client.py", line 196, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: ProcessError: Encountered invalid prev_hash

**Comment by tokyotechlab** [comment]
Here's the sample file I'm feeding to 

{"coin_name": "Zcash", "inputs": [{"address_n": [2147483692, 2147483781, 2147483648, 0, 0], "prev_hash": "02f462a63191f8dc01aea8800d87b1ae8db4154e578677b8c33606f307843a9b", "prev_index": 0, "amount": 4496100, "script_type": 0, "sequence": 4294967293}], "outputs": [{"address_n": null, "address": "t1YaEJ4r4DxUKFRHNkEycfdKFuof4YN1nmL", "amount": 100000, "script_type": 0, "block_hash": null, "block_height": null}, {"address_n": [2147483692, 2147483781, 2147483648, 0, 0], "address": null, "amount": 4296100, "script_type": 0, "block_hash": null, "block_height": null}], "prev_txes": {"02f462a63191f8dc01aea8800d87b1ae8db4154e578677b8c33606f307843a9b": {"version": 4, "inputs": [{"address_n": [], "prev_hash": "4fd1685203e716772683714af49f33d1c6b2028c5fc97440f34b23a2fed4cf28", "prev_index": 0, "script_sig": "473044022070b402ffe4b1612b7e9520052b46c6cd437e9c950009c006eb937473ab8dcf27022027937fd7ea5c561c50932ec1ef4200541d573d34367355d42809d89ca6bae105012103e2fcb3b705b80e89a16c6a3f0db2191d82347df2622a6c038cf94eb86cffe2f8", "sequence": 4294967295, "script_type": null, "multisig": null, "amount": null, "decred_tree": null, "decred_script_version": null, "prev_block_hash_bip115": null, "prev_block_height_bip115": null}], "bin_outputs": [{"amount": 4496100, "script_pubkey": "76a9140a045f124e12c808ab29ac60fa6860fecb1aff9088ac", "decred_script_version": null}], "lock_time": 0, "outputs": [], "inputs_cnt": null, "outputs_cnt": null, "extra_data": "00", "extra_data_len": null, "expiry": 0, "overwintered": true, "version_group_id": 2301567109, "timestamp": null, "branch_id": null}}, "details": {"version": 4, "lock_time": 0}}

**Comment by tokyotechlab** [comment]
It doesn't seem to help if I remove the extra_data and extra_data_len fields.
I've also set extra_data_len to 1, but no luck.

Is there a sample Zcash v4 test cases I can feed to trezorctl sign-tx?

**Comment by matejcik** [comment]
You're not setting `overwintered` and `version_group_id` in tx details. That's invalid.
You _could_ set `extra_data` properly in the previous txes (the current code for that does not work on v3/v4 txes), but that's the wrong solution, because you're creating an invalid transaction anyway.
The errors are misleading, but I'm not sure if python-trezor is the right place to do anything about that.

**Comment by tokyotechlab** [comment]
Setting those parameters in tx details worked. Thank you!
