### ISSUE TITLE
String overflow error when running helloword.py

### ISSUE THREAD

**Issue by Christewart** [trezor/python-trezor#43]
The following error occurs when I enter in my PIN after running `python helloworld.py`
Traceback (most recent call last):
  File "helloworld.py", line 33, in <module>
    main()
  File "helloworld.py", line 27, in main
    address = client.get_address('Bitcoin', bip32_path)
  File "/home/chris/dev/python-trezor/trezorlib/client.py", line 70, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/chris/dev/python-trezor/trezorlib/client.py", line 84, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/chris/dev/python-trezor/trezorlib/client.py", line 405, in get_address
    return self.call(proto.GetAddress(address_n=n, coin_name=coin_name, show_display=show_display))
  File "/home/chris/dev/python-trezor/trezorlib/client.py", line 131, in call
    resp = self.call(msg)
  File "/home/chris/dev/python-trezor/trezorlib/client.py", line 127, in call
    msg = handler(resp)
  File "/home/chris/dev/python-trezor/trezorlib/client.py", line 143, in callback_Failure
    raise CallException(msg.code, msg.message)
trezorlib.client.CallException: (3, u'string overflow')

**Comment by prusnak** [comment]
How long is your PIN? Maximum length is 9 digits.

**Comment by Christewart** [comment]
@prusnak My PIN is 8 digits long. It works just fine with sites like mytrezor.com and wallets like Electrum

**Comment by Christewart** [comment]
I actually tried another Trezor that I have with a 4 digit PIN and also got the same error

**Comment by prusnak** [comment]
Works for me. Are you using latest python-trezor? (`pip install --upgrade trezor`)

**Comment by prusnak** [comment]
Closing. Please reopen if the issue still persists.
