### ISSUE TITLE
python-trezor plus electrum problem with protobuf

### ISSUE THREAD

**Issue by benjunmun** [trezor/python-trezor#47]
In Electrum, opening the new hardware wallet screen results in the following error, which hides the option to create a new Trezor-backed wallet. Installing a new version of protobuf (protobuf-2.6.1) appears to fix the problem. However python-trezor requires 2.5.0 exactly.

```
Error: cannot initialize plugin trezor
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/electrum/plugins.py", line 68, in load_plugin
    p = __import__(full_name, fromlist=['electrum_plugins'])
  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/trezor.py", line 39, in <module>
    import trezorlib.ckd_public as ckd_public
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/ckd_public.py", line 11, in <module>
    import types_pb2 as proto_types
  File "/usr/local/lib/python2.7/dist-packages/trezorlib/types_pb2.py", line 10, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database
```

I've just started playing with this combination, so I'm not sure if the issue is with Electrum or with python-trezor. Apologies if this is mis-filed.

python-trezor was installed directly from the github version. I'm using Electrum 2.5.4.

**Comment by prusnak** [comment]
Fixed in d2e23a126fab0f4587ea62f65fcd8b702940a269. Updated dependency to protobuf-2.6.1. Please reopen if the issue still persist.
