### ISSUE TITLE
electrum trezor plugin related: 

### ISSUE THREAD

**Issue by molecular** [trezor/python-trezor#66]
e8f76ebd03f197bdaee821f26a1a423cad532ccc introduces a problem in my electrum wallet (problem does not occur with previous commit b0e39b571a85dd4a4d04640a4459bb12cddf0666):

To reproduce.

 * start electrum (using -w to open a trezor based wallet)
 * observe popup saying "could not connect to your TREZOR. Verify the calbe is connected and that no other application is iusing it. Try connect again?"

stdout says:
```
[DeviceMgr] scanning devices...
```

in later versions (tag v0.7.0) the behaviour in the gui is the same, but there seems to be an exception

```
[trezor] cannot connect at 0003:004b:00 'Plugin' object does not support indexing
```

finding the place in the code (trezor/plugin.py) and commenting out the catch to actually see the stacktrace reveals:

```
Traceback (most recent call last):
  File "/mnt/maui/home/nick/bitcoin/electrum/gui/qt/util.py", line 550, in run
    result = task.task()
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor/plugin.py", line 138, in get_client
    client = devmgr.client_for_wallet(self, wallet, force_pair)
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/plugins.py", line 399, in client_for_wallet
    return self.force_pair_wallet(plugin, wallet, devices)
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/plugins.py", line 409, in force_pair_wallet
    info = self.select_device(wallet, plugin, devices)
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/plugins.py", line 460, in select_device
    infos = self.unpaired_device_infos(wallet.handler, plugin, devices)
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/plugins.py", line 446, in unpaired_device_infos
    client = self.create_client(device, handler, plugin)
  File "/mnt/maui/home/nick/bitcoin/electrum/lib/plugins.py", line 327, in create_client
    client = plugin.create_client(device, handler)
  File "/mnt/maui/home/nick/bitcoin/electrum/plugins/trezor/plugin.py", line 108, in create_client
    transport = self.HidTransport(pair)
  File "/usr/lib64/python2.7/site-packages/trezor-0.7.0-py2.7.egg/trezorlib/transport_hid.py", line 140, in HidTransport
    transport = path_to_transport(device[0])
TypeError: 'Plugin' object does not support indexing
```

not sure if this is electrum or python-trezor problem. Stopped digging at this point, will use v0.6.13 for now...

**Comment by prusnak** [comment]
Electrum does not work with 0.7.x branch (not sure about master, but released versions are not compatible).

**Comment by molecular** [comment]
I see, thanks.
