### ISSUE TITLE
Not able to run the tests

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#85]
I am getting this error when I try to run the tests on master on Fedora 25:
```
$ python2 setup.py test
running test
running egg_info
writing requirements to trezor.egg-info/requires.txt
writing trezor.egg-info/PKG-INFO
writing top-level names to trezor.egg-info/top_level.txt
writing dependency_links to trezor.egg-info/dependency_links.txt
reading manifest file 'trezor.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'trezor.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    'Operating System :: MacOS :: MacOS X',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 172, in run
    self.run_tests()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 193, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named tests
```

**Comment by prusnak** [comment]
Directory tests contains tests for TREZOR hardware, not for python-trezor package. Removed line with test_suite from setup.py in https://github.com/trezor/python-trezor/commit/5cc9893d6f1800cce79663e41d6ad999de31d8d9
